version: '3'
services:
  xlp:
    build: XLP/
    container_name: XLP_GENERATOR
    privileged: true
    pid: host
    #cgroupns: host
    volumes:
      - /boot/config-5.15.0-84-generic:/boot/config-5.15.0-84-generic:ro
      - /sys/kernel/debug/:/sys/kernel/debug/
    depends_on:
      - collector_server
    networks:
      - mynetwork

  # xlp_dummy:
  #   build: XLP/
  #   container_name: XLP_GENERATOR_DUMMY
  #   privileged: true
  #   pid: host
  #   #cgroupns: host
  #   volumes:
  #     - /boot/config-5.15.0-84-generic:/boot/config-5.15.0-84-generic:ro
  #     - /sys/kernel/debug/:/sys/kernel/debug/
  #   depends_on:
  #     - collector_server
  #   networks:
  #     - mynetwork

  collector_server:
    build:
      context: XLP_COLLECTOR/
    container_name: XLP_COLLECTOR
    hostname: xlp_server
    ports:
      - "8086:8086"
    restart: always
    networks:
      - mynetwork
    volumes:
      - /home/utkalika-ibm/XLP_Distributed/collector_logs:/app/logs
    
networks:
  mynetwork:   # Define the custom network
